### ISSUE TITLE
AttributeError: module 'tensorflow._api.v1.compat.v1.image' has no attribute 'non_max_suppression_with_scores'

### ISSUE THREAD

**Issue by hongrui16** [google/automl#320]
how to solve the fatal error.
any available solution?

**Comment by fsx950223** [comment]
upgrade tensorflow 1.15+

**Comment by hongrui16** [comment]
> upgrade tensorflow 1.15+

after upgrade tensorflow from 1.14 to 1.15, it works.
many thanks
